Objetivos Gerais:
Apresentar os conceitos básicos e aplicações da computação distribuída e paralela, com uma abordagem prática que inclui o uso de plataformas middleware para a construção de aplicações distribuídas.
Metodologia:
Aulas expositivas por vídeo conferência, vídeo aulas assíncronas, análise de artigos, listas de exercícios, e apresentação de ferramentas de suporte aos sistemas paralelos e distribuídos.
Critério de Avaliação:
Dois trabalhos de implementação e experimentação com sistemas paralelos e distribuídos (cada um com peso de 50% na média parcial) (avaliação assíncrona com base em implementação e relatório).
A média final será:
MF = MP, se MP ≥ 7,0.
MF = (PF + MP)/2, se MP < 7,0. (PF é a nota da prova final)
Se MF ≥ 5,0 -> Aprovado.
Se MF < 5,0 -> Reprovado.