version: "3.7"

services:
  ppd: 
    image: openjdk:8
    networks:
        - default
    volumes:
        - .:/home/ppd
    container_name: ppd
    stdin_open: true
    tty: true

  ppd-glassfish: 
    image: glassfish
    networks:
        - default
    ports:
        - "4848:4848"
    volumes:
        - .:/home/ppd
    container_name: ppd-glassfish
    stdin_open: true
    tty: true