// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Guess.proto

package br.inf.ufes.ppd.Crack;

public final class GuessOuterClass {
  private GuessOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GuessOrBuilder extends
      // @@protoc_insertion_point(interface_extends:br.inf.ufes.ppd.Crack.Guess)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 attackNumber = 1;</code>
     * @return Whether the attackNumber field is set.
     */
    boolean hasAttackNumber();
    /**
     * <code>optional int32 attackNumber = 1;</code>
     * @return The attackNumber.
     */
    int getAttackNumber();

    /**
     * <code>optional int32 currentindex = 2;</code>
     * @return Whether the currentindex field is set.
     */
    boolean hasCurrentindex();
    /**
     * <code>optional int32 currentindex = 2;</code>
     * @return The currentindex.
     */
    int getCurrentindex();

    /**
     * <code>optional string key = 3;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <code>optional string key = 3;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 3;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional bytes message = 4;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>optional bytes message = 4;</code>
     * @return The message.
     */
    com.google.protobuf.ByteString getMessage();

    /**
     * <code>optional bool done = 5;</code>
     * @return Whether the done field is set.
     */
    boolean hasDone();
    /**
     * <code>optional bool done = 5;</code>
     * @return The done.
     */
    boolean getDone();

    /**
     * <code>optional string nameSlave = 7;</code>
     * @return Whether the nameSlave field is set.
     */
    boolean hasNameSlave();
    /**
     * <code>optional string nameSlave = 7;</code>
     * @return The nameSlave.
     */
    java.lang.String getNameSlave();
    /**
     * <code>optional string nameSlave = 7;</code>
     * @return The bytes for nameSlave.
     */
    com.google.protobuf.ByteString
        getNameSlaveBytes();
  }
  /**
   * Protobuf type {@code br.inf.ufes.ppd.Crack.Guess}
   */
  public static final class Guess extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:br.inf.ufes.ppd.Crack.Guess)
      GuessOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Guess.newBuilder() to construct.
    private Guess(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Guess() {
      key_ = "";
      message_ = com.google.protobuf.ByteString.EMPTY;
      nameSlave_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Guess();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Guess(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              attackNumber_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              currentindex_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              key_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              message_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              done_ = input.readBool();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              nameSlave_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.inf.ufes.ppd.Crack.GuessOuterClass.internal_static_br_inf_ufes_ppd_Crack_Guess_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.inf.ufes.ppd.Crack.GuessOuterClass.internal_static_br_inf_ufes_ppd_Crack_Guess_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.inf.ufes.ppd.Crack.GuessOuterClass.Guess.class, br.inf.ufes.ppd.Crack.GuessOuterClass.Guess.Builder.class);
    }

    private int bitField0_;
    public static final int ATTACKNUMBER_FIELD_NUMBER = 1;
    private int attackNumber_;
    /**
     * <code>optional int32 attackNumber = 1;</code>
     * @return Whether the attackNumber field is set.
     */
    @java.lang.Override
    public boolean hasAttackNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 attackNumber = 1;</code>
     * @return The attackNumber.
     */
    @java.lang.Override
    public int getAttackNumber() {
      return attackNumber_;
    }

    public static final int CURRENTINDEX_FIELD_NUMBER = 2;
    private int currentindex_;
    /**
     * <code>optional int32 currentindex = 2;</code>
     * @return Whether the currentindex field is set.
     */
    @java.lang.Override
    public boolean hasCurrentindex() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 currentindex = 2;</code>
     * @return The currentindex.
     */
    @java.lang.Override
    public int getCurrentindex() {
      return currentindex_;
    }

    public static final int KEY_FIELD_NUMBER = 3;
    private volatile java.lang.Object key_;
    /**
     * <code>optional string key = 3;</code>
     * @return Whether the key field is set.
     */
    @java.lang.Override
    public boolean hasKey() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string key = 3;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 3;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString message_;
    /**
     * <code>optional bytes message = 4;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes message = 4;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    public static final int DONE_FIELD_NUMBER = 5;
    private boolean done_;
    /**
     * <code>optional bool done = 5;</code>
     * @return Whether the done field is set.
     */
    @java.lang.Override
    public boolean hasDone() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bool done = 5;</code>
     * @return The done.
     */
    @java.lang.Override
    public boolean getDone() {
      return done_;
    }

    public static final int NAMESLAVE_FIELD_NUMBER = 7;
    private volatile java.lang.Object nameSlave_;
    /**
     * <code>optional string nameSlave = 7;</code>
     * @return Whether the nameSlave field is set.
     */
    @java.lang.Override
    public boolean hasNameSlave() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string nameSlave = 7;</code>
     * @return The nameSlave.
     */
    @java.lang.Override
    public java.lang.String getNameSlave() {
      java.lang.Object ref = nameSlave_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nameSlave_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nameSlave = 7;</code>
     * @return The bytes for nameSlave.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameSlaveBytes() {
      java.lang.Object ref = nameSlave_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameSlave_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, attackNumber_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, currentindex_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, key_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, message_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(5, done_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, nameSlave_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, attackNumber_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currentindex_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, key_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, message_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, done_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, nameSlave_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.inf.ufes.ppd.Crack.GuessOuterClass.Guess)) {
        return super.equals(obj);
      }
      br.inf.ufes.ppd.Crack.GuessOuterClass.Guess other = (br.inf.ufes.ppd.Crack.GuessOuterClass.Guess) obj;

      if (hasAttackNumber() != other.hasAttackNumber()) return false;
      if (hasAttackNumber()) {
        if (getAttackNumber()
            != other.getAttackNumber()) return false;
      }
      if (hasCurrentindex() != other.hasCurrentindex()) return false;
      if (hasCurrentindex()) {
        if (getCurrentindex()
            != other.getCurrentindex()) return false;
      }
      if (hasKey() != other.hasKey()) return false;
      if (hasKey()) {
        if (!getKey()
            .equals(other.getKey())) return false;
      }
      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (hasDone() != other.hasDone()) return false;
      if (hasDone()) {
        if (getDone()
            != other.getDone()) return false;
      }
      if (hasNameSlave() != other.hasNameSlave()) return false;
      if (hasNameSlave()) {
        if (!getNameSlave()
            .equals(other.getNameSlave())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasAttackNumber()) {
        hash = (37 * hash) + ATTACKNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getAttackNumber();
      }
      if (hasCurrentindex()) {
        hash = (37 * hash) + CURRENTINDEX_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentindex();
      }
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      if (hasDone()) {
        hash = (37 * hash) + DONE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getDone());
      }
      if (hasNameSlave()) {
        hash = (37 * hash) + NAMESLAVE_FIELD_NUMBER;
        hash = (53 * hash) + getNameSlave().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.inf.ufes.ppd.Crack.GuessOuterClass.Guess prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.inf.ufes.ppd.Crack.Guess}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:br.inf.ufes.ppd.Crack.Guess)
        br.inf.ufes.ppd.Crack.GuessOuterClass.GuessOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.inf.ufes.ppd.Crack.GuessOuterClass.internal_static_br_inf_ufes_ppd_Crack_Guess_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.inf.ufes.ppd.Crack.GuessOuterClass.internal_static_br_inf_ufes_ppd_Crack_Guess_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.inf.ufes.ppd.Crack.GuessOuterClass.Guess.class, br.inf.ufes.ppd.Crack.GuessOuterClass.Guess.Builder.class);
      }

      // Construct using br.inf.ufes.ppd.Crack.GuessOuterClass.Guess.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        attackNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        currentindex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        done_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        nameSlave_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.inf.ufes.ppd.Crack.GuessOuterClass.internal_static_br_inf_ufes_ppd_Crack_Guess_descriptor;
      }

      @java.lang.Override
      public br.inf.ufes.ppd.Crack.GuessOuterClass.Guess getDefaultInstanceForType() {
        return br.inf.ufes.ppd.Crack.GuessOuterClass.Guess.getDefaultInstance();
      }

      @java.lang.Override
      public br.inf.ufes.ppd.Crack.GuessOuterClass.Guess build() {
        br.inf.ufes.ppd.Crack.GuessOuterClass.Guess result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.inf.ufes.ppd.Crack.GuessOuterClass.Guess buildPartial() {
        br.inf.ufes.ppd.Crack.GuessOuterClass.Guess result = new br.inf.ufes.ppd.Crack.GuessOuterClass.Guess(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.attackNumber_ = attackNumber_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.currentindex_ = currentindex_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.message_ = message_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.done_ = done_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.nameSlave_ = nameSlave_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.inf.ufes.ppd.Crack.GuessOuterClass.Guess) {
          return mergeFrom((br.inf.ufes.ppd.Crack.GuessOuterClass.Guess)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.inf.ufes.ppd.Crack.GuessOuterClass.Guess other) {
        if (other == br.inf.ufes.ppd.Crack.GuessOuterClass.Guess.getDefaultInstance()) return this;
        if (other.hasAttackNumber()) {
          setAttackNumber(other.getAttackNumber());
        }
        if (other.hasCurrentindex()) {
          setCurrentindex(other.getCurrentindex());
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000004;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasMessage()) {
          setMessage(other.getMessage());
        }
        if (other.hasDone()) {
          setDone(other.getDone());
        }
        if (other.hasNameSlave()) {
          bitField0_ |= 0x00000020;
          nameSlave_ = other.nameSlave_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.inf.ufes.ppd.Crack.GuessOuterClass.Guess parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.inf.ufes.ppd.Crack.GuessOuterClass.Guess) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int attackNumber_ ;
      /**
       * <code>optional int32 attackNumber = 1;</code>
       * @return Whether the attackNumber field is set.
       */
      @java.lang.Override
      public boolean hasAttackNumber() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 attackNumber = 1;</code>
       * @return The attackNumber.
       */
      @java.lang.Override
      public int getAttackNumber() {
        return attackNumber_;
      }
      /**
       * <code>optional int32 attackNumber = 1;</code>
       * @param value The attackNumber to set.
       * @return This builder for chaining.
       */
      public Builder setAttackNumber(int value) {
        bitField0_ |= 0x00000001;
        attackNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 attackNumber = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttackNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        attackNumber_ = 0;
        onChanged();
        return this;
      }

      private int currentindex_ ;
      /**
       * <code>optional int32 currentindex = 2;</code>
       * @return Whether the currentindex field is set.
       */
      @java.lang.Override
      public boolean hasCurrentindex() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int32 currentindex = 2;</code>
       * @return The currentindex.
       */
      @java.lang.Override
      public int getCurrentindex() {
        return currentindex_;
      }
      /**
       * <code>optional int32 currentindex = 2;</code>
       * @param value The currentindex to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentindex(int value) {
        bitField0_ |= 0x00000002;
        currentindex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 currentindex = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentindex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        currentindex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 3;</code>
       * @return Whether the key field is set.
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string key = 3;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 3;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 3;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 3;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        key_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes message = 4;</code>
       * @return Whether the message field is set.
       */
      @java.lang.Override
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes message = 4;</code>
       * @return The message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <code>optional bytes message = 4;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes message = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }

      private boolean done_ ;
      /**
       * <code>optional bool done = 5;</code>
       * @return Whether the done field is set.
       */
      @java.lang.Override
      public boolean hasDone() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bool done = 5;</code>
       * @return The done.
       */
      @java.lang.Override
      public boolean getDone() {
        return done_;
      }
      /**
       * <code>optional bool done = 5;</code>
       * @param value The done to set.
       * @return This builder for chaining.
       */
      public Builder setDone(boolean value) {
        bitField0_ |= 0x00000010;
        done_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool done = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDone() {
        bitField0_ = (bitField0_ & ~0x00000010);
        done_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object nameSlave_ = "";
      /**
       * <code>optional string nameSlave = 7;</code>
       * @return Whether the nameSlave field is set.
       */
      public boolean hasNameSlave() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string nameSlave = 7;</code>
       * @return The nameSlave.
       */
      public java.lang.String getNameSlave() {
        java.lang.Object ref = nameSlave_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nameSlave_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nameSlave = 7;</code>
       * @return The bytes for nameSlave.
       */
      public com.google.protobuf.ByteString
          getNameSlaveBytes() {
        java.lang.Object ref = nameSlave_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nameSlave_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nameSlave = 7;</code>
       * @param value The nameSlave to set.
       * @return This builder for chaining.
       */
      public Builder setNameSlave(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        nameSlave_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nameSlave = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearNameSlave() {
        bitField0_ = (bitField0_ & ~0x00000020);
        nameSlave_ = getDefaultInstance().getNameSlave();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nameSlave = 7;</code>
       * @param value The bytes for nameSlave to set.
       * @return This builder for chaining.
       */
      public Builder setNameSlaveBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        nameSlave_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:br.inf.ufes.ppd.Crack.Guess)
    }

    // @@protoc_insertion_point(class_scope:br.inf.ufes.ppd.Crack.Guess)
    private static final br.inf.ufes.ppd.Crack.GuessOuterClass.Guess DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.inf.ufes.ppd.Crack.GuessOuterClass.Guess();
    }

    public static br.inf.ufes.ppd.Crack.GuessOuterClass.Guess getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Guess>
        PARSER = new com.google.protobuf.AbstractParser<Guess>() {
      @java.lang.Override
      public Guess parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Guess(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Guess> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Guess> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.inf.ufes.ppd.Crack.GuessOuterClass.Guess getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_inf_ufes_ppd_Crack_Guess_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_br_inf_ufes_ppd_Crack_Guess_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Guess.proto\022\025br.inf.ufes.ppd.Crack\"r\n\005" +
      "Guess\022\024\n\014attackNumber\030\001 \001(\005\022\024\n\014currentin" +
      "dex\030\002 \001(\005\022\013\n\003key\030\003 \001(\t\022\017\n\007message\030\004 \001(\014\022" +
      "\014\n\004done\030\005 \001(\010\022\021\n\tnameSlave\030\007 \001(\tB\027\n\025br.i" +
      "nf.ufes.ppd.Crack"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_br_inf_ufes_ppd_Crack_Guess_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_br_inf_ufes_ppd_Crack_Guess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_br_inf_ufes_ppd_Crack_Guess_descriptor,
        new java.lang.String[] { "AttackNumber", "Currentindex", "Key", "Message", "Done", "NameSlave", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
