// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubAttack.proto

package br.inf.ufes.ppd.Crack;

public final class SubAttackOuterClass {
  private SubAttackOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubAttackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:br.inf.ufes.ppd.Crack.SubAttack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes ciphertext = 1;</code>
     * @return Whether the ciphertext field is set.
     */
    boolean hasCiphertext();
    /**
     * <code>optional bytes ciphertext = 1;</code>
     * @return The ciphertext.
     */
    com.google.protobuf.ByteString getCiphertext();

    /**
     * <code>optional bytes knowntext = 2;</code>
     * @return Whether the knowntext field is set.
     */
    boolean hasKnowntext();
    /**
     * <code>optional bytes knowntext = 2;</code>
     * @return The knowntext.
     */
    com.google.protobuf.ByteString getKnowntext();

    /**
     * <code>optional int32 initialwordindex = 3;</code>
     * @return Whether the initialwordindex field is set.
     */
    boolean hasInitialwordindex();
    /**
     * <code>optional int32 initialwordindex = 3;</code>
     * @return The initialwordindex.
     */
    int getInitialwordindex();

    /**
     * <code>optional int32 finalwordindex = 4;</code>
     * @return Whether the finalwordindex field is set.
     */
    boolean hasFinalwordindex();
    /**
     * <code>optional int32 finalwordindex = 4;</code>
     * @return The finalwordindex.
     */
    int getFinalwordindex();

    /**
     * <code>optional int32 attackNumbe = 5;</code>
     * @return Whether the attackNumbe field is set.
     */
    boolean hasAttackNumbe();
    /**
     * <code>optional int32 attackNumbe = 5;</code>
     * @return The attackNumbe.
     */
    int getAttackNumbe();

    /**
     * <code>optional int32 serverID = 6;</code>
     * @return Whether the serverID field is set.
     */
    boolean hasServerID();
    /**
     * <code>optional int32 serverID = 6;</code>
     * @return The serverID.
     */
    int getServerID();
  }
  /**
   * Protobuf type {@code br.inf.ufes.ppd.Crack.SubAttack}
   */
  public static final class SubAttack extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:br.inf.ufes.ppd.Crack.SubAttack)
      SubAttackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubAttack.newBuilder() to construct.
    private SubAttack(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubAttack() {
      ciphertext_ = com.google.protobuf.ByteString.EMPTY;
      knowntext_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SubAttack();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubAttack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bitField0_ |= 0x00000001;
              ciphertext_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              knowntext_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              initialwordindex_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              finalwordindex_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              attackNumbe_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              serverID_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.inf.ufes.ppd.Crack.SubAttackOuterClass.internal_static_br_inf_ufes_ppd_Crack_SubAttack_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.inf.ufes.ppd.Crack.SubAttackOuterClass.internal_static_br_inf_ufes_ppd_Crack_SubAttack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack.class, br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack.Builder.class);
    }

    private int bitField0_;
    public static final int CIPHERTEXT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString ciphertext_;
    /**
     * <code>optional bytes ciphertext = 1;</code>
     * @return Whether the ciphertext field is set.
     */
    @java.lang.Override
    public boolean hasCiphertext() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes ciphertext = 1;</code>
     * @return The ciphertext.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getCiphertext() {
      return ciphertext_;
    }

    public static final int KNOWNTEXT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString knowntext_;
    /**
     * <code>optional bytes knowntext = 2;</code>
     * @return Whether the knowntext field is set.
     */
    @java.lang.Override
    public boolean hasKnowntext() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes knowntext = 2;</code>
     * @return The knowntext.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKnowntext() {
      return knowntext_;
    }

    public static final int INITIALWORDINDEX_FIELD_NUMBER = 3;
    private int initialwordindex_;
    /**
     * <code>optional int32 initialwordindex = 3;</code>
     * @return Whether the initialwordindex field is set.
     */
    @java.lang.Override
    public boolean hasInitialwordindex() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 initialwordindex = 3;</code>
     * @return The initialwordindex.
     */
    @java.lang.Override
    public int getInitialwordindex() {
      return initialwordindex_;
    }

    public static final int FINALWORDINDEX_FIELD_NUMBER = 4;
    private int finalwordindex_;
    /**
     * <code>optional int32 finalwordindex = 4;</code>
     * @return Whether the finalwordindex field is set.
     */
    @java.lang.Override
    public boolean hasFinalwordindex() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional int32 finalwordindex = 4;</code>
     * @return The finalwordindex.
     */
    @java.lang.Override
    public int getFinalwordindex() {
      return finalwordindex_;
    }

    public static final int ATTACKNUMBE_FIELD_NUMBER = 5;
    private int attackNumbe_;
    /**
     * <code>optional int32 attackNumbe = 5;</code>
     * @return Whether the attackNumbe field is set.
     */
    @java.lang.Override
    public boolean hasAttackNumbe() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 attackNumbe = 5;</code>
     * @return The attackNumbe.
     */
    @java.lang.Override
    public int getAttackNumbe() {
      return attackNumbe_;
    }

    public static final int SERVERID_FIELD_NUMBER = 6;
    private int serverID_;
    /**
     * <code>optional int32 serverID = 6;</code>
     * @return Whether the serverID field is set.
     */
    @java.lang.Override
    public boolean hasServerID() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 serverID = 6;</code>
     * @return The serverID.
     */
    @java.lang.Override
    public int getServerID() {
      return serverID_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBytes(1, ciphertext_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, knowntext_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, initialwordindex_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt32(4, finalwordindex_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt32(5, attackNumbe_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt32(6, serverID_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, ciphertext_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, knowntext_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, initialwordindex_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, finalwordindex_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, attackNumbe_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, serverID_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack)) {
        return super.equals(obj);
      }
      br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack other = (br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack) obj;

      if (hasCiphertext() != other.hasCiphertext()) return false;
      if (hasCiphertext()) {
        if (!getCiphertext()
            .equals(other.getCiphertext())) return false;
      }
      if (hasKnowntext() != other.hasKnowntext()) return false;
      if (hasKnowntext()) {
        if (!getKnowntext()
            .equals(other.getKnowntext())) return false;
      }
      if (hasInitialwordindex() != other.hasInitialwordindex()) return false;
      if (hasInitialwordindex()) {
        if (getInitialwordindex()
            != other.getInitialwordindex()) return false;
      }
      if (hasFinalwordindex() != other.hasFinalwordindex()) return false;
      if (hasFinalwordindex()) {
        if (getFinalwordindex()
            != other.getFinalwordindex()) return false;
      }
      if (hasAttackNumbe() != other.hasAttackNumbe()) return false;
      if (hasAttackNumbe()) {
        if (getAttackNumbe()
            != other.getAttackNumbe()) return false;
      }
      if (hasServerID() != other.hasServerID()) return false;
      if (hasServerID()) {
        if (getServerID()
            != other.getServerID()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCiphertext()) {
        hash = (37 * hash) + CIPHERTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getCiphertext().hashCode();
      }
      if (hasKnowntext()) {
        hash = (37 * hash) + KNOWNTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getKnowntext().hashCode();
      }
      if (hasInitialwordindex()) {
        hash = (37 * hash) + INITIALWORDINDEX_FIELD_NUMBER;
        hash = (53 * hash) + getInitialwordindex();
      }
      if (hasFinalwordindex()) {
        hash = (37 * hash) + FINALWORDINDEX_FIELD_NUMBER;
        hash = (53 * hash) + getFinalwordindex();
      }
      if (hasAttackNumbe()) {
        hash = (37 * hash) + ATTACKNUMBE_FIELD_NUMBER;
        hash = (53 * hash) + getAttackNumbe();
      }
      if (hasServerID()) {
        hash = (37 * hash) + SERVERID_FIELD_NUMBER;
        hash = (53 * hash) + getServerID();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code br.inf.ufes.ppd.Crack.SubAttack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:br.inf.ufes.ppd.Crack.SubAttack)
        br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.inf.ufes.ppd.Crack.SubAttackOuterClass.internal_static_br_inf_ufes_ppd_Crack_SubAttack_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.inf.ufes.ppd.Crack.SubAttackOuterClass.internal_static_br_inf_ufes_ppd_Crack_SubAttack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack.class, br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack.Builder.class);
      }

      // Construct using br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ciphertext_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        knowntext_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        initialwordindex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        finalwordindex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        attackNumbe_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        serverID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.inf.ufes.ppd.Crack.SubAttackOuterClass.internal_static_br_inf_ufes_ppd_Crack_SubAttack_descriptor;
      }

      @java.lang.Override
      public br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack getDefaultInstanceForType() {
        return br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack.getDefaultInstance();
      }

      @java.lang.Override
      public br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack build() {
        br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack buildPartial() {
        br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack result = new br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ciphertext_ = ciphertext_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.knowntext_ = knowntext_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.initialwordindex_ = initialwordindex_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.finalwordindex_ = finalwordindex_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.attackNumbe_ = attackNumbe_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.serverID_ = serverID_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack) {
          return mergeFrom((br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack other) {
        if (other == br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack.getDefaultInstance()) return this;
        if (other.hasCiphertext()) {
          setCiphertext(other.getCiphertext());
        }
        if (other.hasKnowntext()) {
          setKnowntext(other.getKnowntext());
        }
        if (other.hasInitialwordindex()) {
          setInitialwordindex(other.getInitialwordindex());
        }
        if (other.hasFinalwordindex()) {
          setFinalwordindex(other.getFinalwordindex());
        }
        if (other.hasAttackNumbe()) {
          setAttackNumbe(other.getAttackNumbe());
        }
        if (other.hasServerID()) {
          setServerID(other.getServerID());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString ciphertext_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes ciphertext = 1;</code>
       * @return Whether the ciphertext field is set.
       */
      @java.lang.Override
      public boolean hasCiphertext() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bytes ciphertext = 1;</code>
       * @return The ciphertext.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getCiphertext() {
        return ciphertext_;
      }
      /**
       * <code>optional bytes ciphertext = 1;</code>
       * @param value The ciphertext to set.
       * @return This builder for chaining.
       */
      public Builder setCiphertext(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        ciphertext_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes ciphertext = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCiphertext() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ciphertext_ = getDefaultInstance().getCiphertext();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString knowntext_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes knowntext = 2;</code>
       * @return Whether the knowntext field is set.
       */
      @java.lang.Override
      public boolean hasKnowntext() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes knowntext = 2;</code>
       * @return The knowntext.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getKnowntext() {
        return knowntext_;
      }
      /**
       * <code>optional bytes knowntext = 2;</code>
       * @param value The knowntext to set.
       * @return This builder for chaining.
       */
      public Builder setKnowntext(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        knowntext_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes knowntext = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKnowntext() {
        bitField0_ = (bitField0_ & ~0x00000002);
        knowntext_ = getDefaultInstance().getKnowntext();
        onChanged();
        return this;
      }

      private int initialwordindex_ ;
      /**
       * <code>optional int32 initialwordindex = 3;</code>
       * @return Whether the initialwordindex field is set.
       */
      @java.lang.Override
      public boolean hasInitialwordindex() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 initialwordindex = 3;</code>
       * @return The initialwordindex.
       */
      @java.lang.Override
      public int getInitialwordindex() {
        return initialwordindex_;
      }
      /**
       * <code>optional int32 initialwordindex = 3;</code>
       * @param value The initialwordindex to set.
       * @return This builder for chaining.
       */
      public Builder setInitialwordindex(int value) {
        bitField0_ |= 0x00000004;
        initialwordindex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 initialwordindex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInitialwordindex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        initialwordindex_ = 0;
        onChanged();
        return this;
      }

      private int finalwordindex_ ;
      /**
       * <code>optional int32 finalwordindex = 4;</code>
       * @return Whether the finalwordindex field is set.
       */
      @java.lang.Override
      public boolean hasFinalwordindex() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional int32 finalwordindex = 4;</code>
       * @return The finalwordindex.
       */
      @java.lang.Override
      public int getFinalwordindex() {
        return finalwordindex_;
      }
      /**
       * <code>optional int32 finalwordindex = 4;</code>
       * @param value The finalwordindex to set.
       * @return This builder for chaining.
       */
      public Builder setFinalwordindex(int value) {
        bitField0_ |= 0x00000008;
        finalwordindex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 finalwordindex = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFinalwordindex() {
        bitField0_ = (bitField0_ & ~0x00000008);
        finalwordindex_ = 0;
        onChanged();
        return this;
      }

      private int attackNumbe_ ;
      /**
       * <code>optional int32 attackNumbe = 5;</code>
       * @return Whether the attackNumbe field is set.
       */
      @java.lang.Override
      public boolean hasAttackNumbe() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional int32 attackNumbe = 5;</code>
       * @return The attackNumbe.
       */
      @java.lang.Override
      public int getAttackNumbe() {
        return attackNumbe_;
      }
      /**
       * <code>optional int32 attackNumbe = 5;</code>
       * @param value The attackNumbe to set.
       * @return This builder for chaining.
       */
      public Builder setAttackNumbe(int value) {
        bitField0_ |= 0x00000010;
        attackNumbe_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 attackNumbe = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAttackNumbe() {
        bitField0_ = (bitField0_ & ~0x00000010);
        attackNumbe_ = 0;
        onChanged();
        return this;
      }

      private int serverID_ ;
      /**
       * <code>optional int32 serverID = 6;</code>
       * @return Whether the serverID field is set.
       */
      @java.lang.Override
      public boolean hasServerID() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional int32 serverID = 6;</code>
       * @return The serverID.
       */
      @java.lang.Override
      public int getServerID() {
        return serverID_;
      }
      /**
       * <code>optional int32 serverID = 6;</code>
       * @param value The serverID to set.
       * @return This builder for chaining.
       */
      public Builder setServerID(int value) {
        bitField0_ |= 0x00000020;
        serverID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 serverID = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerID() {
        bitField0_ = (bitField0_ & ~0x00000020);
        serverID_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:br.inf.ufes.ppd.Crack.SubAttack)
    }

    // @@protoc_insertion_point(class_scope:br.inf.ufes.ppd.Crack.SubAttack)
    private static final br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack();
    }

    public static br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SubAttack>
        PARSER = new com.google.protobuf.AbstractParser<SubAttack>() {
      @java.lang.Override
      public SubAttack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubAttack(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubAttack> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubAttack> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.inf.ufes.ppd.Crack.SubAttackOuterClass.SubAttack getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_br_inf_ufes_ppd_Crack_SubAttack_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_br_inf_ufes_ppd_Crack_SubAttack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017SubAttack.proto\022\025br.inf.ufes.ppd.Crack" +
      "\"\213\001\n\tSubAttack\022\022\n\nciphertext\030\001 \001(\014\022\021\n\tkn" +
      "owntext\030\002 \001(\014\022\030\n\020initialwordindex\030\003 \001(\005\022" +
      "\026\n\016finalwordindex\030\004 \001(\005\022\023\n\013attackNumbe\030\005" +
      " \001(\005\022\020\n\010serverID\030\006 \001(\005B\027\n\025br.inf.ufes.pp" +
      "d.Crack"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_br_inf_ufes_ppd_Crack_SubAttack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_br_inf_ufes_ppd_Crack_SubAttack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_br_inf_ufes_ppd_Crack_SubAttack_descriptor,
        new java.lang.String[] { "Ciphertext", "Knowntext", "Initialwordindex", "Finalwordindex", "AttackNumbe", "ServerID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
